### ISSUE TITLE
Cannot open compressed file readRDS("./data/shiny-model-fit-dat.RDS")

### ISSUE THREAD

**Issue by Saurat** [Tychobra/shiny-insurance-examples#1]
When downloading the git (clon), and try to run the app. This message is sent:

![captura de pantalla 2019-02-15 a la s 12 15 47](https://user-images.githubusercontent.com/16085599/52876945-418c3b80-311e-11e9-983a-781f04fb243f.png)

- I do have installed the tychobratools libraries and similars.

Help, please.

**Comment by merlinoa** [comment]
Sorry, but unfortunately this particular Shiny app does not come with the necessary data to run it locally.  The data is proprietary, so I could not include it.

**Comment by adliahrz** [comment]
> Sorry, but unfortunately this particular Shiny app does not come with the necessary data to run it locally. The data is proprietary, so I could not include it.

Is it the data is the raw data for this load data? because there two RDS save data that been loaded. 
 
-this the first load data
# load data
dat <- readRDS("**./data/shiny-model-fit-dat.RDS**")

- this the second load data
preds <- readRDS("model.rds")
