### ISSUE TITLE
add Excel Report Option

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/shiny-insurance-examples#2]
Similar to what you did for the Excel workbook for canopy can you add an Excel workbook to the "basic-insurer-dashboard" shiny app in this repo.

The "Create PDF Report" button in the left sidebar should be renamed "Create Report".  After the user clicks on this button, a small modal should pop up.  The modal should have two buttons.  One button to create the pdf report, and another button to create the Excel report.  The modal should also have a cancel button in the modal footer.  The modal should close when the user clicks any of these buttons.  The Excel and PDF reports should be created and downloaded when those buttons are clicked.

**Comment by RichardHHill** [comment]
Finished in commit d1feb156a807c9763da35bf4bbb305a21a6e9bb5

**Comment by merlinoa** [comment]
@RichardHHill I made some updates to the formatting for the Excel report af8a7d169f131c8b7d4b0bec808d2691b8a3c93d.  Can you add multi-row column headers to the 2 Excel Exhibits.  The column headers should be as similar as possible to the column headers in the pdf report.

Maybe a function like this would be nice...

```
create_header_row <- function(col_headers = list(list(col_name = "col_1", col_span = 1), list(col_name = "Col Name to Span 3 Columns", col_span = 3))) {
  # `openxlsx` stuff to make it happen in here
}

```

The above function would create column names above the existing column names in the table.  You could use the `col_span` to specify the number of columns the header should stretch over.

**Comment by RichardHHill** [comment]
Finished in commit 20254760b89a0247a5076b4782c5dc76a1697438
